version: "3.0"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      replicas: 1
      placement:  
        constraints: [node.role == manager]
  node_pub:
    image: pub-node 
    environment:
      BROKER: mqtt
      TOPIC: upb/chat
      PORT: 1883
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]
  node_sub:
    image: sub-node 
    environment:
      BROKER: mqtt
      TOPIC: upb/chat
      PORT: 1883
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]
